#!/usr/bin/env bash
# One-command upgrade after `git pull`: mounts config + vendored extensions
# via a compose override, restarts, migrates the DB, and re-imports content.
#   ./upgrade.sh [admin-username]     (default: Admin)
set -euo pipefail
ADMIN="${1:-Admin}"
if [ ! -f config/LocalSettings.php ]; then
  echo "config/LocalSettings.php not found — run the install wizard first (README steps 1–3)." >&2
  exit 1
fi

cat > docker-compose.override.yml <<'YML'
# Generated by upgrade.sh — mounts the Aurefold config and vendored extensions.
services:
  mediawiki:
    volumes:
      - ./config/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./config/LocalSettings.aurefold.php:/var/www/html/LocalSettings.aurefold.php
      - ./config/aurefold_logo.png:/var/www/html/resources/assets/aurefold_logo.png
      - ./extensions-extra/TemplateStyles:/var/www/html/extensions/TemplateStyles
      - ./extensions-extra/Popups:/var/www/html/extensions/Popups
YML

docker compose up -d --force-recreate mediawiki
echo "Waiting for MediaWiki…"
for i in $(seq 1 30); do
  docker compose exec -T mediawiki php -r 'exit(0);' >/dev/null 2>&1 && break
  sleep 2
done

echo "== Database migrations =="
docker compose exec -T mediawiki php maintenance/run.php update --quick

./import.sh "$ADMIN"
