insert into public.lore_scenes(book_code,chapter_number,scene_order,title,pov_character_id,location_entity_id,summary,knowledge_before,knowledge_after,source_version,state,visibility,metadata)
select 'book-1',v.chapter_no,v.scene_order,v.title,null,null,null,null,v.knowledge_after,'English Master v1.6 / Character & Knowledge Map v1.3','governing','author_only',jsonb_build_object('section_kind',v.section_kind,'protected_remainder',v.protected)
from (values
(1,1,'The Trial of the Goatherd','chapter','Sela refuses performance; Tomas cannot honestly close the trial; “Not I” remains unsaid.','No verified voice.'),
(2,1,'The Woman Against the Stone','chapter','Reader sees Alaine’s private uncertainty and practiced institutional stillness.','Alaine’s experiences remain unverified.'),
(3,1,'The Morning After','chapter','Ordinary life is reclassified around Sela; reverence becomes social pressure.','Meaning remains made by others.'),
(3,2,'The Question in the Margin','interlude','Wren, Perrin and Crown-watch turn Whitehart records into a Jubilee question; commission begins.','Old wording anomaly is non-probative.'),
(4,1,'Harl’s Road','chapter','Family economy, Harl, practical road life and knife relationship are established.','No prophetic framing.'),
(5,1,'The Ledger','chapter','Sela learns how entry creates durable institutional reality.','Her judgment remains absent.'),
(6,1,'Col','chapter','Col’s absence becomes a recorded and personal conflict.','Fate unresolved.'),
(7,1,'The East Shoulder','chapter','Grave exposed and disputed; provenance damaged.','No identity or Eleventh proof.'),
(8,1,'Nothing Happened','chapter','Rumor turns non-event into sign; camp grows.','No authoritative interpretation.'),
(9,1,'The Man Who Writes It Down','chapter','Perrin arrives after a twenty-nine-day journey; attention becomes leverage.','Collector does not own truth.'),
(10,1,'Nobody Ever Asked','chapter','Fen’s erased standing and Nessa history become human rather than procedural abstraction.','No simple restoration.'),
(11,1,'What the Grave No Longer Shows','chapter','Wren reconstructs what evidence can and cannot support.','Grave remains unresolved.'),
(12,1,'Fen Who?','chapter','Name/standing gap becomes visible in ordinary exchange.','Identity is not equivalent to institutional recognition.'),
(13,1,'The Corrected Entry','chapter','Corrections show records can change legal futures without restoring original context.','Correction is not total truth.'),
(14,1,'Not That Way','chapter','Material route/work knowledge overtakes abstract procedure.','No method becomes omniscient.'),
(15,1,'Nine Fares','chapter','Harl departs with nine fares.','Outcome not yet known.'),
(16,1,'Four Accounts of a Rope','chapter','Rescue produces divergent accounts; Harl dies.','No single heroic version owns the event.'),
(17,1,'What Harl Became','chapter','Death is simplified into public story; private grief resists it.','Harl cannot correct the living.'),
(18,1,'The Rule of Six Words','chapter','Alaine grants Sela exclusive speech access to Fen, creating privilege rather than repair.','Fen’s standing is not restored.'),
(19,1,'Lethren','chapter','Dynastic/institutional pressures and Duskport credit enter camp governance.','House relation is not moral verdict.'),
(20,1,'Serenel','chapter','Alaine’s Serenel name becomes public leverage used to shield Sela.','Prestige does not become moral proof.'),
(21,1,'The Price of Water','chapter','Maren, Halvard and Nella systems save lives and create stigma, debt and dependency.','Practical success is not political innocence.'),
(22,1,'What She Never Told Him','chapter','Private withheld information shifts trust.','Silence is not automatically deceit.'),
(23,1,'You Knew What They Would Hear','chapter','Alaine admits knowing how literally true wording would be enlarged.','Truthfulness is not innocence.'),
(24,1,'The First Command','chapter','Sela deliberately uses public authority to find a child and feels the danger of success.','Success does not verify prophecy.'),
(25,1,'Two True Messages','chapter','Selective true information helps both sides militarize.','Neither report alone explains later violence.'),
(26,1,'The Agreement That Almost Worked','chapter','Agreement genuinely holds seven minutes before collapse.','Failure is not inevitable in retrospect.'),
(27,1,'Before the Field','chapter','Armed readiness and spatial pressure harden around Lower Field.','No war declaration is required.'),
(28,1,'The First Arrow','chapter','Wren observes Jeren Tesk release the first identifiable bolt.','Not a complete causal first-aggressor answer.'),
(29,1,'Lower Field','chapter','Crowd conflict outruns single-witness sequence.','No clean heroic battle narrative.'),
(30,1,'The Line That Held','chapter','Aren blocks pursuit; Joric holds a mixed wound lane and dies.','Redemption does not erase prior conduct.'),
(31,1,'The Man Under the Banner','chapter','Violence is experienced through bodies, affiliation and misrecognition.','Banner does not settle blame.'),
(32,1,'Who Won','chapter','Aftermath scale: sixty-four defensible deaths by day seven and more than two hundred under treatment.','Victory remains a political story.'),
(33,1,'The Dead Have Owners','chapter','Bodies, kin, records and burial claims compete.','Ownership of grief is not ownership of history.'),
(34,1,'The Account That Could Start Another War','chapter','Perrin enters his own role; Wren’s handling of Jeren’s name exposes family to consequence.','Accurate record is not harmless or complete.'),
(35,1,'The Price of Mercy','chapter','Tomas and Fen confront the cost of unclosed mercy.','Good intent does not erase harm.'),
(36,1,'Perrin Leaves Whitehart','chapter','Perrin leaves records and questions running after his body leaves.','Departure does not end influence.'),
(37,1,'Nine Days','chapter','Ration horizon is made physical with nine objects; closure pressure narrows choices.','Numbers do not choose morally.'),
(38,1,'The Lawful Thing','chapter','Orla spends her standing to carry and verify Fen’s information; lawful options are clarified.','Fen is not restored by proxy.'),
(39,1,'Unless You Stop It','chapter','Alaine places effective responsibility for stopping closure before Sela; Sela does not stop it.','Silence does not become simple consent.'),
(40,1,'Five Days','chapter','Closed-gate waiting turns policy into hunger, cold, rumor and bodies.','No single intent controls the crowd.'),
(41,1,'The Gate','chapter','Fifth-morning crush; Gate opens inward; Ivet is fatally injured; nine/twelve counts diverge.','First aggressor and exact mechanics remain unresolved.'),
(42,1,'The Washing','chapter','Sela names and washes Ivet; death remains ordinary and permanent.','No martyrdom or afterlife proof.'),
(43,1,'The Keeper','chapter','Fen processes treatment records and receives Wilda’s Col account.','Col remains unconfirmed.'),
(44,1,'The Divided Report','chapter','Wren separates observations, source key and future-use risk; nine/twelve stay distinct.','No neutral final record.'),
(45,1,'That’s How You Know','chapter','Nella’s staged grain arrives; false quotation and Corrin consequence show denial can be turned into proof.','Quotation remains false even when socially effective.'),
(46,1,'The Blank Page','chapter','Tomas publicly ends the test without judgment, gives the key to Osric; Tam gives Sela Harl’s knife.','Blank page is not a positive classification.'),
(47,1,'East','chapter','Alaine does not call Sela back; Sela leaves east; Bell sounds beyond ordinary count.','Bell cause/meaning and Col remain unresolved.')
) as v(chapter_no,scene_order,title,section_kind,knowledge_after,protected)
on conflict (book_code,chapter_number,scene_order) do update set title=excluded.title,knowledge_after=excluded.knowledge_after,source_version=excluded.source_version,state=excluded.state,visibility=excluded.visibility,metadata=excluded.metadata;
