with d as (select id from public.canon_documents where slug='aurefold-constitution-v1-9')
insert into public.canon_locks(lock_number,document_id,canonical_text,state,visibility)
select v.lock_number,d.id,v.canonical_text,'ratified'::public.canon_state,'author_only'::public.canon_visibility from d cross join (values
(1,'Aurefold is the world''s name.'),
(2,'Ten Great Civilizations represented by Great Houses.'),
(3,'Historical leadership philosophies inspire each civilization.'),
(4,'Civilization -> Great House -> Dynasty.'),
(5,'The Concord / Empire of Aurelion precedes the Houses.'),
(6,'Hall of Eleven has no throne.'),
(7,'Civilizations began as philosophical schools.'),
(8,'Wars begin as philosophical disagreements.'),
(9,'History is never objective.'),
(10,'Central question: How should humanity live together?'),
(11,'Aurefold feels discovered, not invented.'),
(12,'The world is beautiful; people are dangerous.'),
(13,'Aurefold is mature in subject and consequence. The series is not required to avoid graphic brutality, disturbing material, or shock, but darkness must remain one register of a living world rather than the whole identity of the series.'),
(14,'History has consequences.'),
(15,'Adults built this world.'),
(16,'Shock, horror, disgust, transgression, and attention are legitimate narrative effects, including as a scene''s primary immediate purpose. Major material must still earn its place in the larger work.'),
(17,'Violence may reveal character, culture, power, history, fear, bodily reality, or the cost of institutions, and it may be depicted in explicit detail when the scene benefits from that detail.'),
(18,'Violence has personality.'),
(19,'Monsters often smile.'),
(20,'Every villain believes they are necessary.'),
(21,'Every chapter must evoke emotion.'),
(22,'Beauty makes tragedy hurt.'),
(23,'Every character is someone''s world.'),
(24,'Violence changes people, bodies, relationships, institutions, memory, and history. Its consequences may be physical, psychological, sexual, social, legal, political, or generational.'),
(25,'Every civilization has virtue and flaw.'),
(26,'The reader chooses.'),
(27,'The world exists beyond the protagonists.'),
(28,'Every scene earns its place.'),
(29,'A forgotten Eleventh House once existed and was deliberately erased from history.'),
(30,'Magic in Aurefold is never objectively confirmed; every apparent supernatural event must remain open to at least one credible non-magical interpretation.'),
(31,'Death is permanent in Aurefold; literal resurrection does not exist.'),
(32,'Aurefold shares one technological baseline: 40% Renaissance, 30% Late Medieval, 20% Antiquity, and 10% unique Aurefold innovation; civilizations differ through specialization, not separate historical eras.'),
(33,'Faith possesses political, cultural, and emotional power regardless of whether its supernatural claims are true.'),
(34,'The Ashen Crown is a later claimant polity and is neither one of the Ten recognized Great Houses nor the erased Eleventh House.'),
(35,'Aurelion is both the official administrative project name and the canonical name associated with the ancient pre-House Concord or Empire; this dual use is intentional and does not name the world, which is Aurefold.'),
(36,'The Concord / Empire of Aurelion fell approximately two thousand years before Book One. The "year 396 after the Unification" dating used in Book One refers to a later historical event and is not the founding or fall of the ancient Aurelion Empire.'),
(37,'Years in the present era are counted A.U. (After the Unification). Book One begins in 396 A.U., four years before the Four-Hundred-Year Jubilee. The War of the Unification occurred long after the fall of the ancient Aurelion Empire.'),
(38,'The ten recognized Great Houses and their governing philosophies are: Blackthorn - Intellect; Ashbourne - Courage; Whitehart - Faith; Stormrider - Unity; Ravenshade - Information; Ironvale - Innovation; Blackcrest - the Victor''s History; Stonebear - Honor; Tidebreaker - Knowledge; and Phoenix - the Future.'),
(39,'Every recognized Great House must create genuine good and genuine victims. None of the Ten is the singular evil of Aurefold, and each must be defensible by an intelligent and decent person within the story.'),
(40,'The people of the Ashen Crown remain human and morally varied, but its ideology of purification, classification, dehumanization, and extermination is not treated as an equally valid leadership philosophy among the Ten.'),
(41,'Magic cannot be reliably repeated, measured, summoned, taught as a dependable technique, or used on command. If an effect can be reproduced consistently, it is technique rather than magic. Aurefold contains no hidden final magic system awaiting complete explanation.'),
(42,'The forgotten Eleventh House shall never be named with certainty. Its philosophy, seat, descendants, loyalties, and complete fate shall never be objectively confirmed, and every proposed truth about it must pass through incomplete or unreliable evidence.'),
(43,'Both a human explanation and a mystical explanation for the erasure of the Eleventh must remain viable. Neither explanation may permanently disprove the other.'),
(44,'No single relic, grave, text, bloodline, character, institution, or recurring symbol may prove the Eleventh or explain every House''s relationship to it. Charged references to the number eleven are finite and require explicit author approval before new instances enter canon.'),
(45,'Great Houses embody leadership philosophies, but individual characters do not exist as perfect representatives or mouthpieces for their Houses. Characters are governed by personal appetites, loyalties, fears, contradictions, relationships, and material needs.'),
(46,'Aurefold is built as a living continental world, not a closed island-stage. Geography extends beyond the first mapped regions, and political, cultural, and commercial frontiers continue beyond the limits of any single atlas.'),
(47,'The Banner-lands are the historical heartland of the Ten Great Houses, not the whole continent or the whole world.'),
(48,'Civilizations and peoples exist beyond the political world known to the Ten Great Houses, but the inhabitants of the House territories do not know this with certainty. Fragmentary accounts, disputed maps, strange goods, sailors'' testimony, and corrupted traditions suggest a wider world without proving its nature or extent. Any connection between those peoples and the erased Eleventh House remains unconfirmed.'),
(49,'Each recognized Great House possesses a historically established territorial domain shaped by its civilization and philosophy. These House territories form the principal political geography of the known world, but may contain disputed marches, subordinate regions, autonomous cities, enclaves, minority cultures, and lesser rulers.'),
(50,'City-states, merchant leagues, valley combines, kingdoms, clans, religious seats, republics, free ports, and frontier communities possess independent agency and are not merely servants of the Ten.'),
(51,'Political borders change through war, marriage, migration, treaty, debt, climate, trade, and institutional collapse. No political map of Aurefold is permanently final.'),
(52,'Every map has a date, maker, patron, purpose, and omission. Maps may disagree without one automatically being false.'),
(53,'Leadership philosophies and precursor civilizations existed before the Unification. The recognized Great House order was formalized at 0 A.U. Dynasties arose, changed, or replaced one another afterward.'),
(54,'A dynasty may fall, merge, divide, or be replaced without ending the civilization or Great House it temporarily governs.'),
(55,'A Great House is recognized only when it possesses an established civilization, a recognized territorial domain, a legitimate governing institution, and formal recognition under the post-Unification Concord. Recognition cannot be achieved merely by conquest, wealth, ancestry, or self-declaration.'),
(56,'Each Great House possesses a succession system shaped by its philosophy. Succession may be hereditary, elective, tested, appointed, acclaimed, institutional, or contested.'),
(57,'Before a Great House becomes the dominant civilization of a novel, its law, economy, family structure, ritual life, succession, military tradition, ordinary labor, regional variation, virtue, victim class, and internal dissent must be established.'),
(58,'Real historical inspirations remain hidden structural foundations. Aurefold may draw from documented conduct as well as ideals - including conquest, massacre, torture, sexual violence, captivity, coercive marriage, enslavement, execution, terror, political murder, institutional abuse, reform, mercy, and statecraft - but no House may reproduce its inspiration through recognizable names, ethnicity, biography, heraldry, quotation, or direct one-to-one historical imitation. Disputed historical claims must remain identified as disputed in authorial research.'),
(59,'One widespread administrative and trade language developed after the Unification and is understood across the House territories, while regional languages remain dominant in private and local life. The novels render most speech in English translation, while culturally irreducible words, titles, prayers, and concepts may remain untranslated. Aurefold contains four major language families, with numerous regional languages and dialects.'),
(60,'All recognized peoples use the A.U. calendar for official dating. The year contains ten months of thirty-six days each, followed by five intercalary days that belong to no month. A.U. - After the Unification - is used throughout the known House territories.'),
(61,'Aurefold contains at least six continentally significant religious traditions, alongside regional cults, ancestor practices, household rites, philosophical faiths, and local syncretic traditions. Whitehart preserves one influential religious tradition but does not control or define religion throughout Aurefold. A House may contain several religions, and one religion may cross multiple House territories.'),
(62,'Ordinary overland travel averages twenty to thirty kilometers per day. Mounted official relays may carry urgent messages approximately one hundred kilometers per day along maintained routes. Rivers and coastal shipping are generally faster and cheaper than roads. Mountains, winter, war, damaged infrastructure, and political borders may reduce communication to a fraction of those speeds.'),
(63,'New geography enters canon through lived routes, trade, migration, testimony, historical necessity, and narrative need. The complete continent is not designed as a finished board before the stories reach it.'),
(64,'The Tenfold Compact is the formal post-Unification legal order created at 0 A.U. The phrase "post-Unification Concord" in Canon Lock #055 refers to this Compact and is entirely distinct from the ancient Concord / Empire of Aurelion.'),
(65,'The Unification ended a prolonged multi-sided war through negotiated settlement, mutual exhaustion, and shared necessity. No single ruler conquered or founded the unified order alone.'),
(66,'The Tenfold Compact has no permanent emperor and no supreme hereditary throne. Shared matters are governed through councils, temporary offices, negotiated coalitions, and institutions whose authority depends upon continued House recognition.'),
(67,'The Hall of Eleven is the supreme chamber of recognition, oath, arbitration, and constitutional ratification. It contains eleven places but no throne; ten are associated with the recognized Great Houses, while the meaning of the remaining place is disputed and officially unexplained.'),
(68,'The Tenfold Compact recognizes exactly ten Great Houses at any one time. A claimant cannot create an additional recognized seat through conquest, wealth, ancestry, or self-declaration.'),
(69,'Great House recognition may be suspended or contested through collective constitutional action, but no legal act can erase a civilization, its people, or its historical existence. The lawful removal of a Great House has never occurred in the A.U. era.'),
(70,'The Four-Hundred-Year Jubilee renews the public history and political legitimacy of the Tenfold Compact. House oaths, territorial claims, recognized successions, disputed precedents, and the official Chronicle are formally presented or ratified during the Jubilee.'),
(71,'Territorial subjecthood and civilizational House identity are related but not identical. A person may live under one House''s laws while retaining another cultural identity, mixed ancestry, local allegiance, or no meaningful House affiliation.'),
(72,'Movement between House territories is possible but politically unequal. Rights of settlement, marriage, inheritance, trade, worship, and office vary by House, local authority, social rank, and historical treaty.'),
(73,'The Ashen Crown does not claim to be the erased Eleventh House. It claims that the Tenfold order has failed and must be replaced by a single purified successor state capable of ending division permanently.'),
(74,'Official history teaches that there have always been Ten Great Houses. Evidence of an Eleventh survives only through disputed architecture, corrupted records, forbidden traditions, misremembered names, and anomalies that institutions explain away.'),
(75,'Approximately sixteen centuries separate the fall of ancient Aurelion from the War of the Unification. During this period, precursor civilizations rose, divided, migrated, merged, and transformed into the cultures later formalized as the recognized Great Houses.'),
(76,'All objectively confirmed civilizations and peoples of Aurefold are human. No non-human intelligent species is objectively confirmed; accounts of such beings remain folklore, mistranslation, disputed testimony, or encounters not fully understood.'),
(77,'No creature is objectively confirmed to be supernatural. Aurefold may contain rare, dangerous, unfamiliar, or supposedly impossible animals, but every creature must retain a credible biological, historical, mistaken, or legendary interpretation.'),
(78,'Gods, souls, divine judgment, and the afterlife are never objectively confirmed or disproved. Religious experiences may transform individuals and civilizations without providing measurable supernatural proof.'),
(79,'No prophecy is objectively verified as supernatural foreknowledge, and no character is confirmed as a uniquely destined savior. Prophecy acts through interpretation, political use, coincidence, selective memory, and self-fulfilment.'),
(80,'A Great House is a civilization and political identity, not a race or single ethnicity. Every House contains multiple regional peoples, ancestries, minorities, dialects, and mixed communities, while ethnic and cultural groups may cross House borders.'),
(81,'A Great House''s foundational philosophy persists across history but is never interpreted uniformly. Dynasties, institutions, factions, reformers, traditionalists, and ordinary people may refine, distort, weaponize, betray, or rediscover it.'),
(82,'The Tenfold Compact governs Great House recognition, inter-House treaties, territorial disputes, shared trade routes, major war, diplomatic protections, constitutional arbitration, and relations between the Ten. Domestic law remains primarily under House, regional, municipal, religious, and local authority.'),
(83,'The Tenfold Compact possesses no permanent imperial army. It may authorize temporary coalition forces, shared patrols, limited constitutional guards, and emergency levies, but military strength remains primarily controlled by the Great Houses and lesser powers.'),
(84,'Each recognized Great House possesses one equal formal voice in the Hall of Eleven regardless of territory, population, wealth, or military strength. The unexplained eleventh place possesses no recognized vote.'),
(85,'Torture, sexual violence, mutilation, coercion, abuse, captivity, execution, and other human cruelty may be shown on-page in explicit sensory detail. Such material may deliberately create shock, attention, revulsion, dread, or spectacle. Non-consensual sexual violence is never framed as erotic reward or pornographic titillation, and major acts must retain human consequence; victims remain people rather than disposable texture.')
) as v(lock_number,canonical_text)
on conflict (lock_number) do update set document_id=excluded.document_id, canonical_text=excluded.canonical_text, state=excluded.state, visibility=excluded.visibility;
