create table if not exists public.character_arc_tracks (
  id uuid primary key default gen_random_uuid(),
  book_code text not null references public.lore_books(code) on delete cascade,
  character_id uuid not null references public.lore_entities(id) on delete cascade,
  status text not null default 'active' check (status in ('active','superseded')),
  created_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(book_code, character_id)
);

create table if not exists public.character_arc_assessments (
  id uuid primary key default gen_random_uuid(),
  track_id uuid not null references public.character_arc_tracks(id) on delete cascade,
  source_revision_label text not null,
  manuscript_version_id uuid null references public.manuscript_versions(id) on delete set null,
  source_sha256 text null,
  assessment_status text not null default 'draft' check (assessment_status in ('draft','reviewed','superseded')),
  arc_question text null,
  starting_belief text null,
  starting_desire text null,
  starting_fear text null,
  defense_strategy text null,
  latent_need text null,
  ending_belief text null,
  ending_desire text null,
  ending_fear text null,
  changed_strategy text null,
  primary_relationships text null,
  arc_summary text null,
  notes text null,
  assessed_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(track_id, source_revision_label)
);

create table if not exists public.character_arc_beats (
  id uuid primary key default gen_random_uuid(),
  assessment_id uuid not null references public.character_arc_assessments(id) on delete cascade,
  scene_id uuid not null references public.lore_scenes(id) on delete cascade,
  manuscript_section_id uuid null references public.manuscript_sections(id) on delete set null,
  source_body_sha256 text null,
  beat_type text not null check (beat_type in ('setup','pressure','choice','consequence','relationship_shift','revelation','setback','commitment','turning_point','payoff','other')),
  significance text not null default 'medium' check (significance in ('low','medium','high','turning_point')),
  agency_mode text not null default 'reactive' check (agency_mode in ('none','reactive','active','decisive')),
  state_before text null,
  pressure text null,
  choice_action text null,
  cost_text text null,
  state_after text null,
  belief_effect text null,
  relationship_effect text null,
  notes text null,
  created_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(assessment_id, scene_id)
);

create table if not exists public.character_arc_assessment_history (
  id bigint generated by default as identity primary key,
  assessment_id uuid not null references public.character_arc_assessments(id) on delete cascade,
  event_kind text not null,
  previous_data jsonb null,
  new_data jsonb null,
  note text null,
  actor_user_id uuid null,
  created_at timestamptz not null default now()
);

create table if not exists public.character_arc_beat_history (
  id bigint generated by default as identity primary key,
  assessment_id uuid not null references public.character_arc_assessments(id) on delete cascade,
  beat_id uuid null,
  scene_id uuid null references public.lore_scenes(id) on delete set null,
  event_kind text not null,
  previous_data jsonb null,
  new_data jsonb null,
  note text null,
  actor_user_id uuid null,
  created_at timestamptz not null default now()
);

create index if not exists idx_character_arc_tracks_character on public.character_arc_tracks(character_id);
create index if not exists idx_character_arc_tracks_book on public.character_arc_tracks(book_code);
create index if not exists idx_character_arc_assessments_track on public.character_arc_assessments(track_id);
create index if not exists idx_character_arc_assessments_version on public.character_arc_assessments(manuscript_version_id);
create index if not exists idx_character_arc_beats_assessment on public.character_arc_beats(assessment_id);
create index if not exists idx_character_arc_beats_scene on public.character_arc_beats(scene_id);

alter table public.character_arc_tracks enable row level security;
alter table public.character_arc_assessments enable row level security;
alter table public.character_arc_beats enable row level security;
alter table public.character_arc_assessment_history enable row level security;
alter table public.character_arc_beat_history enable row level security;

drop policy if exists character_arc_tracks_author_read on public.character_arc_tracks;
create policy character_arc_tracks_author_read on public.character_arc_tracks for select to authenticated using (public.is_aurefold_author());
drop policy if exists character_arc_assessments_author_read on public.character_arc_assessments;
create policy character_arc_assessments_author_read on public.character_arc_assessments for select to authenticated using (public.is_aurefold_author());
drop policy if exists character_arc_beats_author_read on public.character_arc_beats;
create policy character_arc_beats_author_read on public.character_arc_beats for select to authenticated using (public.is_aurefold_author());
drop policy if exists character_arc_assessment_history_author_read on public.character_arc_assessment_history;
create policy character_arc_assessment_history_author_read on public.character_arc_assessment_history for select to authenticated using (public.is_aurefold_author());
drop policy if exists character_arc_beat_history_author_read on public.character_arc_beat_history;
create policy character_arc_beat_history_author_read on public.character_arc_beat_history for select to authenticated using (public.is_aurefold_author());

revoke all on public.character_arc_tracks from anon;
revoke all on public.character_arc_assessments from anon;
revoke all on public.character_arc_beats from anon;
revoke all on public.character_arc_assessment_history from anon;
revoke all on public.character_arc_beat_history from anon;
grant select on public.character_arc_tracks, public.character_arc_assessments, public.character_arc_beats, public.character_arc_assessment_history, public.character_arc_beat_history to authenticated;

create or replace view public.author_character_arc_assessments as
with current_versions as (
  select distinct on (book_code) book_code,id,version_label,source_sha256
  from public.manuscript_versions
  where is_current
  order by book_code, imported_at desc
), beat_stats as (
  select assessment_id,
         count(*) as beat_count,
         count(*) filter (where significance='turning_point' or beat_type='turning_point') as turning_point_count,
         count(*) filter (where agency_mode='decisive') as decisive_choice_beats,
         count(*) filter (where coalesce(nullif(trim(relationship_effect),''),'') <> '') as relationship_shift_beats
  from public.character_arc_beats
  group by assessment_id
)
select a.id as assessment_id,t.id as track_id,t.book_code,t.character_id,e.slug as character_slug,e.name as character_name,
       a.source_revision_label,a.manuscript_version_id,a.source_sha256,a.assessment_status,
       case when a.assessment_status='superseded' then 'superseded'
            when cv.id is not null and (a.manuscript_version_id is distinct from cv.id or a.source_sha256 is distinct from cv.source_sha256) then 'stale'
            else a.assessment_status end as effective_status,
       cv.id as current_version_id,cv.version_label as current_version_label,cv.source_sha256 as current_source_sha256,
       a.arc_question,a.starting_belief,a.starting_desire,a.starting_fear,a.defense_strategy,a.latent_need,
       a.ending_belief,a.ending_desire,a.ending_fear,a.changed_strategy,a.primary_relationships,a.arc_summary,a.notes,
       coalesce(bs.beat_count,0) as beat_count,coalesce(bs.turning_point_count,0) as turning_point_count,
       coalesce(bs.decisive_choice_beats,0) as decisive_choice_beats,coalesce(bs.relationship_shift_beats,0) as relationship_shift_beats,
       a.updated_at
from public.character_arc_assessments a
join public.character_arc_tracks t on t.id=a.track_id
join public.lore_entities e on e.id=t.character_id
left join current_versions cv on cv.book_code=t.book_code
left join beat_stats bs on bs.assessment_id=a.id;

create or replace view public.author_character_arc_beats as
with current_versions as (
  select distinct on (book_code) book_code,id,version_label
  from public.manuscript_versions where is_current order by book_code,imported_at desc
), current_sections as (
  select ms.lore_scene_id, ms.id as section_id, snap.body_sha256, snap.manuscript_version_id
  from public.manuscript_sections ms
  join public.manuscript_section_snapshots snap on snap.section_id=ms.id
  join current_versions cv on cv.id=snap.manuscript_version_id
)
select b.id as beat_id,b.assessment_id,t.book_code,t.character_id,e.slug as character_slug,e.name as character_name,
       s.id as scene_id,s.chapter_number,s.scene_order,s.title,
       b.beat_type,b.significance,b.agency_mode,b.state_before,b.pressure,b.choice_action,b.cost_text,b.state_after,b.belief_effect,b.relationship_effect,b.notes,
       b.manuscript_section_id,b.source_body_sha256,cs.section_id as current_section_id,cs.body_sha256 as current_body_sha256,
       case when aa.effective_status='stale' then 'stale'
            when b.source_body_sha256 is not null and cs.body_sha256 is distinct from b.source_body_sha256 then 'stale'
            else 'current' end as effective_state,
       sc.effective_status as scene_scorecard_status,sc.choice_weight,sc.emotional_change,sc.relationship_change,sc.material_consequence,sc.reversal_strength,
       case when sc.effective_status='reviewed' and b.agency_mode='decisive' and sc.choice_weight in ('none','minor') then true else false end as agency_scorecard_mismatch,
       case when sc.effective_status='reviewed' and b.beat_type='relationship_shift' and sc.relationship_change in ('none','subtle') then true else false end as relationship_scorecard_mismatch,
       case when sc.effective_status='reviewed' and b.significance='turning_point'
                  and sc.choice_weight in ('none','minor')
                  and sc.emotional_change in ('none','subtle')
                  and sc.relationship_change in ('none','subtle')
                  and sc.material_consequence in ('none','subtle')
                  and sc.reversal_strength in ('none','subtle') then true else false end as turning_point_scorecard_mismatch,
       b.updated_at
from public.character_arc_beats b
join public.character_arc_assessments a on a.id=b.assessment_id
join public.character_arc_tracks t on t.id=a.track_id
join public.lore_entities e on e.id=t.character_id
join public.lore_scenes s on s.id=b.scene_id
join public.author_character_arc_assessments aa on aa.assessment_id=a.id
left join current_sections cs on cs.lore_scene_id=s.id
left join public.author_scene_scorecards sc on sc.scene_id=s.id;

create or replace view public.author_character_arc_queue as
with candidates as (
  select s.book_code,s.pov_character_id as character_id from public.lore_scenes s where s.pov_character_id is not null
  union
  select s.book_code,se.entity_id from public.lore_scene_entities se join public.lore_scenes s on s.id=se.scene_id join public.lore_entities e on e.id=se.entity_id where e.entity_type='character'
  union
  select i.book_code,ie.entity_id from public.editorial_issue_entities ie join public.editorial_issues i on i.id=ie.issue_id join public.lore_entities e on e.id=ie.entity_id where e.entity_type='character' and i.status not in ('resolved','wont_fix','superseded')
  union
  select book_code,character_id from public.character_arc_tracks where status='active'
), linked as (
  select c.book_code,c.character_id,
    (select count(*) from public.lore_scenes s where s.book_code=c.book_code and s.pov_character_id=c.character_id) as pov_units,
    (select count(distinct se.scene_id) from public.lore_scene_entities se join public.lore_scenes s on s.id=se.scene_id where s.book_code=c.book_code and se.entity_id=c.character_id) as linked_units,
    (select count(*) from public.editorial_issue_entities ie join public.editorial_issues i on i.id=ie.issue_id where i.book_code=c.book_code and ie.entity_id=c.character_id and i.status not in ('resolved','wont_fix','superseded')) as active_editorial_issues,
    (select count(*) from public.editorial_issue_entities ie join public.editorial_issues i on i.id=ie.issue_id where i.book_code=c.book_code and ie.entity_id=c.character_id and i.status not in ('resolved','wont_fix','superseded') and i.severity in ('high','critical')) as high_editorial_issues
  from candidates c
), current_assessment as (
  select distinct on (book_code,character_id) *
  from public.author_character_arc_assessments
  order by book_code,character_id,case when effective_status='stale' then 1 else 0 end,updated_at desc
)
select l.book_code,l.character_id,e.slug as character_slug,e.name as character_name,
       l.pov_units,l.linked_units,l.active_editorial_issues,l.high_editorial_issues,
       (l.high_editorial_issues*10 + l.active_editorial_issues*3 + l.pov_units*2 + l.linked_units) as priority_score,
       ca.assessment_id,ca.source_revision_label,ca.effective_status as arc_status,ca.beat_count,ca.turning_point_count,ca.decisive_choice_beats,ca.relationship_shift_beats
from linked l
join public.lore_entities e on e.id=l.character_id
left join current_assessment ca on ca.book_code=l.book_code and ca.character_id=l.character_id;

create or replace view public.author_character_arc_gap_metrics as
with current_beats as (
  select b.*, lag(scene_order) over(partition by assessment_id order by scene_order) as previous_scene_order
  from public.author_character_arc_beats b
  where effective_state='current'
), agg as (
  select assessment_id,
         count(*) as current_beat_count,
         min(scene_order) as first_beat_order,
         max(scene_order) as last_beat_order,
         max(greatest(scene_order-coalesce(previous_scene_order,scene_order)-1,0)) as max_story_units_between_beats
  from current_beats group by assessment_id
)
select a.assessment_id,a.book_code,a.character_id,a.character_name,a.effective_status,
       coalesce(agg.current_beat_count,0) as current_beat_count,agg.first_beat_order,agg.last_beat_order,coalesce(agg.max_story_units_between_beats,0) as max_story_units_between_beats
from public.author_character_arc_assessments a
left join agg on agg.assessment_id=a.assessment_id;

create or replace view public.author_character_arc_graph_edges as
with ordered as (
  select b.*,lag(beat_id) over(partition by assessment_id order by scene_order) as from_beat_id,
         lag(scene_id) over(partition by assessment_id order by scene_order) as from_scene_id,
         lag(scene_order) over(partition by assessment_id order by scene_order) as from_scene_order,
         lag(beat_type) over(partition by assessment_id order by scene_order) as from_beat_type
  from public.author_character_arc_beats b where effective_state='current'
)
select assessment_id,character_id,character_name,from_beat_id,beat_id as to_beat_id,from_scene_id,scene_id as to_scene_id,
       from_scene_order,scene_order as to_scene_order,from_beat_type,beat_type as to_beat_type,
       greatest(scene_order-coalesce(from_scene_order,scene_order)-1,0) as story_units_between
from ordered where from_beat_id is not null;

create or replace view public.author_character_arc_health as
with queue as (select * from public.author_character_arc_queue),
current_assessment as (
  select distinct on (book_code,character_id) * from public.author_character_arc_assessments
  order by book_code,character_id,case when effective_status='stale' then 1 else 0 end,updated_at desc
), beat_flags as (
  select assessment_id,
         count(*) filter(where effective_state='current') as current_beats,
         count(*) filter(where effective_state='stale') as stale_beats,
         count(*) filter(where agency_scorecard_mismatch or relationship_scorecard_mismatch or turning_point_scorecard_mismatch) as scorecard_mismatch_signals
  from public.author_character_arc_beats group by assessment_id
)
select q.book_code,
       count(*) as candidate_characters,
       count(*) filter(where ca.assessment_id is not null) as tracked_characters,
       count(*) filter(where ca.effective_status='reviewed') as reviewed_current,
       count(*) filter(where ca.effective_status='draft') as draft_current,
       count(*) filter(where ca.effective_status='stale') as stale_assessments,
       count(*) filter(where ca.assessment_id is null) as unassessed_characters,
       coalesce(sum(bf.current_beats),0) as current_beats,
       coalesce(sum(bf.stale_beats),0) as stale_beats,
       coalesce(sum(bf.scorecard_mismatch_signals),0) as scorecard_mismatch_signals
from queue q
left join current_assessment ca on ca.book_code=q.book_code and ca.character_id=q.character_id
left join beat_flags bf on bf.assessment_id=ca.assessment_id
group by q.book_code;

grant select on public.author_character_arc_assessments, public.author_character_arc_beats, public.author_character_arc_queue, public.author_character_arc_gap_metrics, public.author_character_arc_graph_edges, public.author_character_arc_health to authenticated;
revoke all on public.author_character_arc_assessments, public.author_character_arc_beats, public.author_character_arc_queue, public.author_character_arc_gap_metrics, public.author_character_arc_graph_edges, public.author_character_arc_health from anon;

create or replace function public.author_upsert_character_arc_assessment(
  p_book_code text,
  p_character_id uuid,
  p_assessment_status text,
  p_arc_question text default null,
  p_starting_belief text default null,
  p_starting_desire text default null,
  p_starting_fear text default null,
  p_defense_strategy text default null,
  p_latent_need text default null,
  p_ending_belief text default null,
  p_ending_desire text default null,
  p_ending_fear text default null,
  p_changed_strategy text default null,
  p_primary_relationships text default null,
  p_arc_summary text default null,
  p_notes text default null,
  p_note text default null
) returns uuid
language plpgsql security definer set search_path='public','pg_temp' as $$
declare
  v_track_id uuid;
  v_version public.manuscript_versions%rowtype;
  v_revision text;
  v_existing public.character_arc_assessments%rowtype;
  v_id uuid;
  v_event text;
begin
  if not public.is_aurefold_author() then raise exception 'Aurefold author role required'; end if;
  if p_assessment_status not in ('draft','reviewed','superseded') then raise exception 'invalid assessment status'; end if;
  if not exists(select 1 from public.lore_books where code=p_book_code) then raise exception 'unknown book'; end if;
  if not exists(select 1 from public.lore_entities where id=p_character_id and entity_type='character') then raise exception 'unknown character'; end if;

  if p_assessment_status='reviewed' and (
    nullif(trim(coalesce(p_arc_question,'')),'') is null or
    nullif(trim(coalesce(p_starting_belief,'')),'') is null or
    nullif(trim(coalesce(p_starting_desire,'')),'') is null or
    nullif(trim(coalesce(p_starting_fear,'')),'') is null or
    nullif(trim(coalesce(p_ending_belief,'')),'') is null or
    nullif(trim(coalesce(p_arc_summary,'')),'') is null
  ) then raise exception 'reviewed arc assessments require arc question, starting belief/desire/fear, ending belief and arc summary'; end if;

  insert into public.character_arc_tracks(book_code,character_id,created_by)
  values(p_book_code,p_character_id,auth.uid())
  on conflict(book_code,character_id) do update set updated_at=now()
  returning id into v_track_id;

  select * into v_version from public.manuscript_versions where book_code=p_book_code and is_current order by imported_at desc limit 1;
  v_revision := coalesce(v_version.version_label,'governing-working');

  select * into v_existing from public.character_arc_assessments where track_id=v_track_id and source_revision_label=v_revision for update;
  if found then
    update public.character_arc_assessments set
      manuscript_version_id=v_version.id, source_sha256=v_version.source_sha256,
      assessment_status=p_assessment_status,arc_question=p_arc_question,starting_belief=p_starting_belief,
      starting_desire=p_starting_desire,starting_fear=p_starting_fear,defense_strategy=p_defense_strategy,latent_need=p_latent_need,
      ending_belief=p_ending_belief,ending_desire=p_ending_desire,ending_fear=p_ending_fear,changed_strategy=p_changed_strategy,
      primary_relationships=p_primary_relationships,arc_summary=p_arc_summary,notes=p_notes,assessed_by=auth.uid(),updated_at=now()
    where id=v_existing.id returning id into v_id;
    v_event := case when p_assessment_status='reviewed' and v_existing.assessment_status<>'reviewed' then 'reviewed'
                    when p_assessment_status='draft' and v_existing.assessment_status='reviewed' then 'reopened'
                    when p_assessment_status='superseded' then 'superseded' else 'updated' end;
    insert into public.character_arc_assessment_history(assessment_id,event_kind,previous_data,new_data,note,actor_user_id)
    select v_id,v_event,to_jsonb(v_existing),to_jsonb(a),p_note,auth.uid() from public.character_arc_assessments a where a.id=v_id;
  else
    insert into public.character_arc_assessments(track_id,source_revision_label,manuscript_version_id,source_sha256,assessment_status,
      arc_question,starting_belief,starting_desire,starting_fear,defense_strategy,latent_need,ending_belief,ending_desire,ending_fear,
      changed_strategy,primary_relationships,arc_summary,notes,assessed_by)
    values(v_track_id,v_revision,v_version.id,v_version.source_sha256,p_assessment_status,
      p_arc_question,p_starting_belief,p_starting_desire,p_starting_fear,p_defense_strategy,p_latent_need,p_ending_belief,p_ending_desire,p_ending_fear,
      p_changed_strategy,p_primary_relationships,p_arc_summary,p_notes,auth.uid()) returning id into v_id;
    insert into public.character_arc_assessment_history(assessment_id,event_kind,new_data,note,actor_user_id)
    select v_id,case when p_assessment_status='reviewed' then 'reviewed' else 'created' end,to_jsonb(a),p_note,auth.uid() from public.character_arc_assessments a where a.id=v_id;
  end if;
  return v_id;
end $$;

create or replace function public.author_upsert_character_arc_beat(
  p_assessment_id uuid,
  p_scene_id uuid,
  p_beat_type text,
  p_significance text,
  p_agency_mode text,
  p_state_before text default null,
  p_pressure text default null,
  p_choice_action text default null,
  p_cost_text text default null,
  p_state_after text default null,
  p_belief_effect text default null,
  p_relationship_effect text default null,
  p_notes text default null,
  p_note text default null
) returns uuid
language plpgsql security definer set search_path='public','pg_temp' as $$
declare
  v_book_code text;
  v_scene_book text;
  v_version_id uuid;
  v_section_id uuid;
  v_body_hash text;
  v_existing public.character_arc_beats%rowtype;
  v_id uuid;
begin
  if not public.is_aurefold_author() then raise exception 'Aurefold author role required'; end if;
  if p_beat_type not in ('setup','pressure','choice','consequence','relationship_shift','revelation','setback','commitment','turning_point','payoff','other') then raise exception 'invalid beat type'; end if;
  if p_significance not in ('low','medium','high','turning_point') then raise exception 'invalid significance'; end if;
  if p_agency_mode not in ('none','reactive','active','decisive') then raise exception 'invalid agency mode'; end if;

  select t.book_code into v_book_code from public.character_arc_assessments a join public.character_arc_tracks t on t.id=a.track_id where a.id=p_assessment_id;
  if v_book_code is null then raise exception 'unknown arc assessment'; end if;
  select book_code into v_scene_book from public.lore_scenes where id=p_scene_id;
  if v_scene_book is distinct from v_book_code then raise exception 'scene belongs to another book'; end if;

  select id into v_version_id from public.manuscript_versions where book_code=v_book_code and is_current order by imported_at desc limit 1;
  if v_version_id is not null then
    select ms.id,snap.body_sha256 into v_section_id,v_body_hash
    from public.manuscript_sections ms join public.manuscript_section_snapshots snap on snap.section_id=ms.id and snap.manuscript_version_id=v_version_id
    where ms.lore_scene_id=p_scene_id order by snap.ordinal limit 1;
  end if;

  select * into v_existing from public.character_arc_beats where assessment_id=p_assessment_id and scene_id=p_scene_id for update;
  if found then
    update public.character_arc_beats set manuscript_section_id=v_section_id,source_body_sha256=v_body_hash,beat_type=p_beat_type,
      significance=p_significance,agency_mode=p_agency_mode,state_before=p_state_before,pressure=p_pressure,choice_action=p_choice_action,
      cost_text=p_cost_text,state_after=p_state_after,belief_effect=p_belief_effect,relationship_effect=p_relationship_effect,notes=p_notes,updated_at=now()
    where id=v_existing.id returning id into v_id;
    insert into public.character_arc_beat_history(assessment_id,beat_id,scene_id,event_kind,previous_data,new_data,note,actor_user_id)
    select p_assessment_id,v_id,p_scene_id,'updated',to_jsonb(v_existing),to_jsonb(b),p_note,auth.uid() from public.character_arc_beats b where b.id=v_id;
  else
    insert into public.character_arc_beats(assessment_id,scene_id,manuscript_section_id,source_body_sha256,beat_type,significance,agency_mode,
      state_before,pressure,choice_action,cost_text,state_after,belief_effect,relationship_effect,notes,created_by)
    values(p_assessment_id,p_scene_id,v_section_id,v_body_hash,p_beat_type,p_significance,p_agency_mode,
      p_state_before,p_pressure,p_choice_action,p_cost_text,p_state_after,p_belief_effect,p_relationship_effect,p_notes,auth.uid()) returning id into v_id;
    insert into public.character_arc_beat_history(assessment_id,beat_id,scene_id,event_kind,new_data,note,actor_user_id)
    select p_assessment_id,v_id,p_scene_id,'created',to_jsonb(b),p_note,auth.uid() from public.character_arc_beats b where b.id=v_id;
  end if;
  return v_id;
end $$;

create or replace function public.author_remove_character_arc_beat(p_beat_id uuid,p_note text default null) returns uuid
language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_existing public.character_arc_beats%rowtype;
begin
  if not public.is_aurefold_author() then raise exception 'Aurefold author role required'; end if;
  select * into v_existing from public.character_arc_beats where id=p_beat_id for update;
  if not found then raise exception 'unknown arc beat'; end if;
  insert into public.character_arc_beat_history(assessment_id,beat_id,scene_id,event_kind,previous_data,note,actor_user_id)
  values(v_existing.assessment_id,v_existing.id,v_existing.scene_id,'removed',to_jsonb(v_existing),p_note,auth.uid());
  delete from public.character_arc_beats where id=p_beat_id;
  return p_beat_id;
end $$;

revoke execute on function public.author_upsert_character_arc_assessment(text,uuid,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text) from public,anon;
revoke execute on function public.author_upsert_character_arc_beat(uuid,uuid,text,text,text,text,text,text,text,text,text,text,text,text) from public,anon;
revoke execute on function public.author_remove_character_arc_beat(uuid,text) from public,anon;
grant execute on function public.author_upsert_character_arc_assessment(text,uuid,text,text,text,text,text,text,text,text,text,text,text,text,text,text,text) to authenticated;
grant execute on function public.author_upsert_character_arc_beat(uuid,uuid,text,text,text,text,text,text,text,text,text,text,text,text) to authenticated;
grant execute on function public.author_remove_character_arc_beat(uuid,text) to authenticated;
